// Comprehensive Food Knowledge Base for Eco-AI
// Based on provided food lists and common pantry items

window.FOOD_DATABASE = [
    // FRUITS
    { name: "Açaí berries", category: "Fruit", shelfLife: 3 },
    { name: "Apples", category: "Fruit", shelfLife: 30 },
    { name: "Apricots", category: "Fruit", shelfLife: 5 },
    { name: "Asian pears", category: "Fruit", shelfLife: 14 },
    { name: "Avocados", category: "Fruit", shelfLife: 4 },
    { name: "Bananas", category: "Fruit", shelfLife: 5 },
    { name: "Blackberry", category: "Fruit", shelfLife: 3 },
    { name: "Blueberry", category: "Fruit", shelfLife: 7 },
    { name: "Boysenberry", category: "Fruit", shelfLife: 3 },
    { name: "Cantaloupe", category: "Fruit", shelfLife: 7 },
    { name: "Cranberries", category: "Fruit", shelfLife: 21 },
    { name: "Currants", category: "Fruit", shelfLife: 7 },
    { name: "Durian", category: "Fruit", shelfLife: 4 },
    { name: "Figs", category: "Fruit", shelfLife: 3 },
    { name: "Gala apples", category: "Fruit", shelfLife: 30 },
    { name: "Grapes", category: "Fruit", shelfLife: 10 },
    { name: "Grapefruit", category: "Fruit", shelfLife: 21 },
    { name: "Guava", category: "Fruit", shelfLife: 5 },
    { name: "Honeydew", category: "Fruit", shelfLife: 7 },
    { name: "Kiwi", category: "Fruit", shelfLife: 14 },
    { name: "Lemons", category: "Fruit", shelfLife: 21 },
    { name: "Limes", category: "Fruit", shelfLife: 21 },
    { name: "Mango", category: "Fruit", shelfLife: 5 },
    { name: "Melon", category: "Fruit", shelfLife: 7 },
    { name: "Nectarines", category: "Fruit", shelfLife: 5 },
    { name: "Orange", category: "Fruit", shelfLife: 21 },
    { name: "Papaya", category: "Fruit", shelfLife: 5 },
    { name: "Passionfruit", category: "Fruit", shelfLife: 7 },
    { name: "Peaches", category: "Fruit", shelfLife: 5 },
    { name: "Pears", category: "Fruit", shelfLife: 7 },
    { name: "Pineapple", category: "Fruit", shelfLife: 5 },
    { name: "Plum", category: "Fruit", shelfLife: 5 },
    { name: "Pomegranate", category: "Fruit", shelfLife: 30 },
    { name: "Raspberry", category: "Fruit", shelfLife: 2 },
    { name: "Satsuma", category: "Fruit", shelfLife: 14 },
    { name: "Starfruit", category: "Fruit", shelfLife: 5 },
    { name: "Strawberry", category: "Fruit", shelfLife: 3 },
    { name: "Watermelon", category: "Fruit", shelfLife: 7 },

    // VEGETABLES
    { name: "Artichokes", category: "Vegetables", shelfLife: 7 },
    { name: "Asparagus", category: "Vegetables", shelfLife: 4 },
    { name: "Aubergine", category: "Vegetables", shelfLife: 5 },
    { name: "Beets", category: "Vegetables", shelfLife: 14 },
    { name: "Bell pepper", category: "Vegetables", shelfLife: 7 },
    { name: "Bok choy", category: "Vegetables", shelfLife: 5 },
    { name: "Broccoli", category: "Vegetables", shelfLife: 7 },
    { name: "Brussels sprouts", category: "Vegetables", shelfLife: 7 },
    { name: "Cabbage", category: "Vegetables", shelfLife: 21 },
    { name: "Carrots", category: "Vegetables", shelfLife: 21 },
    { name: "Cauliflower", category: "Vegetables", shelfLife: 7 },
    { name: "Celery", category: "Vegetables", shelfLife: 14 },
    { name: "Corn", category: "Vegetables", shelfLife: 3 },
    { name: "Cucumber", category: "Vegetables", shelfLife: 7 },
    { name: "Eggplant", category: "Vegetables", shelfLife: 5 },
    { name: "Garlic", category: "Vegetables", shelfLife: 120 },
    { name: "Green beans", category: "Vegetables", shelfLife: 7 },
    { name: "Kale", category: "Vegetables", shelfLife: 7 },
    { name: "Leeks", category: "Vegetables", shelfLife: 10 },
    { name: "Lettuce", category: "Vegetables", shelfLife: 5 },
    { name: "Mushrooms", category: "Vegetables", shelfLife: 5 },
    { name: "Okra", category: "Vegetables", shelfLife: 3 },
    { name: "Onion", category: "Vegetables", shelfLife: 60 },
    { name: "Potato", category: "Vegetables", shelfLife: 60 },
    { name: "Pumpkin", category: "Vegetables", shelfLife: 30 },
    { name: "Radish", category: "Vegetables", shelfLife: 14 },
    { name: "Spinach", category: "Vegetables", shelfLife: 5 },
    { name: "Squash", category: "Vegetables", shelfLife: 30 },
    { name: "Sweet potato", category: "Vegetables", shelfLife: 21 },
    { name: "Tomato", category: "Vegetables", shelfLife: 7 },
    { name: "Zucchini", category: "Vegetables", shelfLife: 5 },

    // MEAT & SEAFOOD
    { name: "Anchovies", category: "Meat", shelfLife: 180 }, // Canned/Jarred usually
    { name: "Bacon", category: "Meat", shelfLife: 7 },
    { name: "Beef", category: "Meat", shelfLife: 4 },
    { name: "Chicken breast", category: "Meat", shelfLife: 2 },
    { name: "Chicken wings", category: "Meat", shelfLife: 2 },
    { name: "Cod", category: "Meat", shelfLife: 2 },
    { name: "Crab", category: "Meat", shelfLife: 2 },
    { name: "Duck", category: "Meat", shelfLife: 2 },
    { name: "Ham", category: "Meat", shelfLife: 5 },
    { name: "Lamb", category: "Meat", shelfLife: 4 },
    { name: "Lobster", category: "Meat", shelfLife: 2 },
    { name: "Mahi-mahi", category: "Meat", shelfLife: 2 },
    { name: "Pork", category: "Meat", shelfLife: 4 },
    { name: "Salmon", category: "Meat", shelfLife: 2 },
    { name: "Sardines", category: "Meat", shelfLife: 180 },
    { name: "Sausage", category: "Meat", shelfLife: 3 },
    { name: "Shrimp", category: "Meat", shelfLife: 2 },
    { name: "Steak", category: "Meat", shelfLife: 4 },
    { name: "Tuna", category: "Meat", shelfLife: 2 },
    { name: "Turkey", category: "Meat", shelfLife: 2 },

    // DAIRY & EGGS
    { name: "Asiago cheese", category: "Dairy", shelfLife: 30 },
    { name: "Butter", category: "Dairy", shelfLife: 60 },
    { name: "Cheddar cheese", category: "Dairy", shelfLife: 30 },
    { name: "Cream cheese", category: "Dairy", shelfLife: 14 },
    { name: "Eggs", category: "Dairy", shelfLife: 30 },
    { name: "Feta", category: "Dairy", shelfLife: 14 },
    { name: "Milk", category: "Dairy", shelfLife: 7 },
    { name: "Mozzarella", category: "Dairy", shelfLife: 7 },
    { name: "Parmesan", category: "Dairy", shelfLife: 120 },
    { name: "Ricotta", category: "Dairy", shelfLife: 7 },
    { name: "Sour cream", category: "Dairy", shelfLife: 21 },
    { name: "Swiss cheese", category: "Dairy", shelfLife: 21 },
    { name: "Yogurt", category: "Dairy", shelfLife: 14 },

    // PANTRY & GRAINS
    { name: "Almonds", category: "Pantry", shelfLife: 180 },
    { name: "Bagel", category: "Bakery", shelfLife: 5 },
    { name: "Barley", category: "Grains", shelfLife: 365 },
    { name: "Basmati rice", category: "Grains", shelfLife: 730 },
    { name: "Beans", category: "Pantry", shelfLife: 730 },
    { name: "Bread", category: "Bakery", shelfLife: 5 }, // Fresh
    { name: "Cashews", category: "Pantry", shelfLife: 180 },
    { name: "Couscous", category: "Grains", shelfLife: 365 },
    { name: "Flour", category: "Pantry", shelfLife: 365 },
    { name: "Honey", category: "Pantry", shelfLife: 3650 },
    { name: "Lentils", category: "Pantry", shelfLife: 730 },
    { name: "Oatmeal", category: "Grains", shelfLife: 365 },
    { name: "Pasta", category: "Grains", shelfLife: 730 },
    { name: "Peanuts", category: "Pantry", shelfLife: 180 },
    { name: "Quinoa", category: "Grains", shelfLife: 365 },
    { name: "Walnuts", category: "Pantry", shelfLife: 180 }
];
